### PR TITLE
Fix some obvious typos, and then some more [Editorial] type problems

### PR DESCRIPTION
**Pull request by jupdike**

### CODE REVIEW

**Comment by acabal** [comment]
Have you had a chance to check the page scans for some of these changes? At least some of the "don't"s are that way in print. Can you confirm each change?

**Comment by jupdike** [comment]
The actual typos if you care are in the first commit:

It very common -> It is very common
good follow -> good fellow
millions off people -> millions of people

I did not check the page scans for these. Am I right in understanding that the goal of SE is not to follow the printed edition even if the printed edition contains obvious typos (doesn't PG do this sometimes)?

You can skip the other changes, but you may consider reading those passages (second commit) and verifying that a modern reader would expect punctuation in the places I mentioned, page scans or not. That is fine if it is outside the mission of SE or if a higher goal is not to risk changing the meaning of the text. (Or you can pick more suitable punctuation if you agree that it is necessary.)

In the future I will just list what typos I noticed on the mailing list, and you can choose the changes you care about since it is hard for me to know exactly how to balance the goals of preserving the original text versus modernizing it the way a modern editor might do.

(It doesn't help that GitHub doesn't show the character-by-character diff, which would make some of this more clear.)

**Comment by acabal** [comment]
Obvious typos we can fix. Not a problem. The three you listed sound good.

Adding/changing punctuation is a *maybe*, usually leaning towards no. I think it really depends, and one must be very careful. For example, your addition of `:` after Samson I don't think is grammatical; and if you examine the page scans, you'll see that there's actually a typo in the transcription, where a missing em dash between `locks his` makes the same sentence read correctly.

Maybe the rule here is to check the page scans first if punctuation appears questionable, because it may just be a transcription error. So, if you check the page scans in the other places where you adjusted punctuation, maybe you'll find some clarifying omissions.

Correcting `don't` is also a little questionable, because when they occur so often in the print then they're unlikely to be typos, and rather a matter of prose style. Probably calculated to make him sound folksy to his presumably poor and uneducated audience.

**Comment by acabal** [comment]
Will you be able to review this pull request? I can't edit pull requests myself, but if I fix the typos myself and check the page scans in a separate commit then your name won't be on it as a committer.

**Comment by jupdike** [comment]
Sorry I have been busy with family stuff. I don’t mind if my name is not listed as a committer. If you can take care of it I would be happy to see the text corrected but if not I think I can check back in the next few days if you haven’t had a chance and I can put in a new clean commit with just the three typos and restoring any punctuation from the page scans.


On Apr 13, 2020, at 7:54 PM, Alex Cabal <notifications@github.com> wrote:

﻿
Will you be able to review this pull request? I can't edit pull requests myself, but if I fix the typos myself and check the page scans in a separate commit then your name won't be on it as a committer.

**Comment by acabal** [comment]
Fixed in a4d0f36. You have a good eye, all of the additions you made were in fact transcription errors (but missing em dashes instead of colons).

**Comment by jupdike** [comment]
Thanks for putting in the fixes. I am sorry I ran out of time to check
against the page scans. Lock-down with a toddler! Thanks again for all your
work on SE.

**Pull request closed without merging**
